creation de la page d'accueil sans intégration de données
uwp-squad/livecoding-uwp pull request #11
Opened 2016-09-26 20:40 UTC by aristid-lavri

juste un aperçu de ce que j'ai fait en attendant

2016-09-26 21:08 UTC, Odonno commented
Ok, voici la liste des choses que l'on pourrait améliorer : 

- [ ] l'image de l'utilisateur (par défaut), je pense qu'on peut réutiliser celle du site : https://www.livecoding.tv/static/img/userdashboard-img.png

2016-09-26 21:09 UTC, aristid-lavri commented
ok pas de soucis , si tas d'autres remarques

2016-09-26 21:10 UTC, Odonno commented on LIvecoding-uwp/LIvecoding-uwp/App.xaml.cs
> +                    rootFrame.Navigate(typeof(LoginView), e.Arguments);
Par défaut, je pense qu'on devrait conserver la page principale comme étant la MainPage. Si on a besoin de se connecter, on exécutera une navigation vers LoginPage au besoin.

Renommer LoginView en LoginPage du coup.

2016-09-26 21:12 UTC, Odonno commented on LIvecoding-uwp/LIvecoding-uwp/Models/IRepository.cs
> +    public interface IRepository
Je ne vois pas l'utilité de cette classe concernant l'utilisation de MVVM.

2016-09-26 21:12 UTC, Odonno commented on LIvecoding-uwp/LIvecoding-uwp/Models/MenuItem.cs
> +    public class MenuItem
Idem. Pas utile à mon sens.

2016-09-26 21:13 UTC, Odonno commented on LIvecoding-uwp/LIvecoding-uwp/Models/MenuRepository.cs
> +    public class MenuRepository:IRepository
Idem. La liste du menu devrait être faite en XAML. Avec le Hamburger menu.

2016-09-26 21:14 UTC, Odonno commented on LIvecoding-uwp/LIvecoding-uwp/ViewModels/IViewModelBase.cs
> +    public class IViewModelBase :ViewModelBase
Il me semble que la méthode `RaisePropertyChanged` fasse la même chose dans MVVMLight. Pourquoi cet ajout ?

2016-09-26 21:14 UTC, Odonno commented on LIvecoding-uwp/LIvecoding-uwp/ViewModels/LoginViewModel.cs
> +            //chargePageCommand = new RelayCommand<RoutedEventArgs>(OnPageLoaded);
Commentaires à supprimer.

2016-09-26 21:15 UTC, Odonno commented on LIvecoding-uwp/LIvecoding-uwp/Views/LiveStreamView.xaml.cs
> +    public sealed partial class LiveStreamView : Page
LiveStreamPage et non View

2016-09-26 21:15 UTC, Odonno commented on LIvecoding-uwp/LIvecoding-uwp/Views/LoginView.xaml.cs
> +    public sealed partial class LoginView : Page
LoginPage et non View

2016-09-26 21:17 UTC, Odonno commented on LIvecoding-uwp/LIvecoding-uwp/Views/UserControls/VideoControl.xaml.cs
> +        public VideoControl()
A l'heure actuelle, je ne sais pas s'il est nécessaire de créer un contrôle vidéo. En effet, ayant travailler sur l'API, je pense qu'on pourra intégrer une WebView, ou mieux encore un contrôle natif de vidéo. Contrôle à supprimer, ou à conserver pour une autre PR.

2016-09-26 21:17 UTC, Odonno requested changes
Des changements à faire.

2016-09-26 21:21 UTC, Odonno commented
J'ai redéfini le scope de la PR autour de l'intégration de MVVM.

2016-09-26 21:25 UTC, aristid-lavri commented on LIvecoding-uwp/LIvecoding-uwp/Views/UserControls/VideoControl.xaml.cs
> +        public VideoControl()
en fait c'est pas un control video mais juste un aperçu des video live avec le thumbnails 
sur l'app android c'est quand on click sur cet element que s'ouvre le lecteur

2016-09-26 21:28 UTC, Odonno commented on LIvecoding-uwp/LIvecoding-uwp/Views/UserControls/VideoControl.xaml.cs
> +        public VideoControl()
Ok, je vois ce que tu veux dire. A mon sens, tu es allé au delà de la PR. En fait, le thumbnail, ce sera dans un DataTemplate à intégrer dans la page qui convient. C'est une bonne idée qu'il faudra conserver pour une prochaine PR.

2016-09-26 21:43 UTC, aristid-lavri commented on LIvecoding-uwp/LIvecoding-uwp/Models/IRepository.cs
> +    public interface IRepository
rien avoir avc MVVM juste utilisé pour avoir une interface qui permette juste le nécessaire sur les manipulations des données a venir

2016-09-27 06:55 UTC, Odonno commented on LIvecoding-uwp/LIvecoding-uwp/Models/IRepository.cs
> +    public interface IRepository
D'accord. A réfléchir pour une autre PM du coup.

2016-09-27 09:31 UTC, Odonno commented
@aristid-lavri Le gif et l'ancienne image sont toujours présentes dans la solution. Tu peux les supprimer.

2016-09-27 10:55 UTC, Odonno commented on LIvecoding-uwp/LIvecoding-uwp/Models/LiveStreamSerializer.cs
> +    class LiveStreamSerializer
Cet objet existe déjà dans le package que j'ai développé. Il me semble que c'est dans le namespace `LivecodingApi.Models`. Utilise l'objet LiveStream dans la librairie plutôt que de recréer les objets une seconde. :)

2016-09-27 10:56 UTC, Odonno commented on LIvecoding-uwp/LIvecoding-uwp/Models/LiveStreamSerializer.cs
> +    class LiveStreamSerializer
Cet objet existe déjà dans le package que j'ai développé. Il me semble que c'est dans le namespace `LivecodingApi.Models`. Utilise l'objet LiveStream dans la librairie plutôt que de recréer les objets une seconde fois. :)

2016-09-27 10:56 UTC, Odonno commented on LIvecoding-uwp/LIvecoding-uwp/Models/LiveStreamSerializer.cs
> +    class LiveStreamSerializer
Cet objet existe déjà dans le package que j'ai développé. Il me semble que c'est dans le namespace `LivecodingApi.Models`. Utilise l'objet LiveStream dans la librairie plutôt que de recréer les objets une seconde fois. :)

2016-09-27 17:26 UTC, Odonno commented
C'est déjà mieux. En ce qui concerne les évolutions du code, j'ai quelques questions : 

- Pourquoi tu utilises le pattern Repository ? Dans notre cas, il est tout à fait inutile puisque nous n'utilisons pas de base de données mais une API. Une `ObservableCollection ` aurait fait l'affaire.
- Pourquoi tu as supprimé la MainPage ?

2016-09-27 17:36 UTC, aristid-lavri commented
Le paterne repository n'est pas utilisé qu'avec des base de données 
dans notre cas bien vrai qu'on utilise une api mais le fait d'avoir un repository donne une surcouche d'abstraction et on ne manipulera que les données dans les vues ( on na pas besoin d'appeler l'api dans la vu)
ainsi on respecte le MVVM 

- [ ] pour la mainPage j'ai juste pas fait expres (question d'habitude) mais je vais la remettre

2016-09-27 17:42 UTC, Odonno commented
Ok, je comprends ton raisonnement. Avoir une couche est parfois bénéfique, surtout dans des application ayant des dépendances fortes avec des API ou des bases de données, effectivement.

Dans notre cas, étant que nous construisons un client léger, notre objectif est de consommer tout simplement les données sur chaque page et donc sur chaque ViewModel. Concrètement, sur la page LiveStreams par exemple, tu charges une collection de LiveStream à partir de l'API et rien de plus.

En clair, c'est ton ViewModel directement qui fait appel à l'API et c'est la vue qui consomme les propriétés et les méthodes du ViewModel. Une couche d'abstraction n'est pas nécessaire, du moins pour le moment.

2016-09-27 18:08 UTC, aristid-lavri commented
ok je vois mais c'est bon d'être prévoyant :) mais c'est ok

2016-09-27 18:26 UTC, Odonno commented
Certes. Mais anticiper un trop grand nombre de fonctionnalités résulte en un grand nombre de gaspillage. Le scope de la PR est sur MVVMLight, je pense qu'elle va faire plus que cela, ce qui est dommageable.

Dans tous les cas, ce qui est fait est fait. Il ne reste plus qu'à corriger certaines choses et ce sera parfait, j'en suis sûr.

2016-12-12 10:15 UTC, Odonno commented
Je sais que cela fait un moment que la PR a été démarrée. J'aimerais savoir si on la continue ou s'il serait préférable de l'arrêter et d'en commencer une autre sachant que l'ajout de MVVMLight est censé être indolore. Qu'en penses-tu ?

2016-12-12 10:20 UTC, aristid-lavri commented
Ca serait bien de reprendre comme ca @andre726  comprendra mieux et il pourra avancer en même temps que nous

2016-12-12 10:21 UTC, andre726 commented
j'avoue que je ne sais pas faire de mvvmlight, je ne connais pas encore tout ces principe, vous penser a quoi comme pr?

2016-12-12 11:33 UTC, aristid-lavri commented
je pense qu'il s'agit de reprendre celle-ci

2016-12-12 13:37 UTC, Odonno commented
Dans ce cas, est-ce que ça vous dérange si je fais des modifications sur cette branche ? Concernant MVVMLight bien sûr.

2016-12-12 13:41 UTC, aristid-lavri commented
pas du tout

2016-12-12 13:50 UTC, andre726 commented
aucun souci

2016-12-12 19:42 UTC, Odonno approved these changes

2016-12-12 19:45 UTC, Odonno commented
Voilà, j'ai fait les changements. J'en ai profité pour revenir sur un modèle simple avec 2 pages : LoginPage et MainPage. Je suppose qu'on va partir avec hamburger donc le page contenant ce contrôle sera sans doute la MainPage.

J'ai également rajouté un NavigationService propre à MVVMLight.

2016-12-13 14:22 UTC, Odonno commented
Dites-moi ce que vous en pensez, histoire que je puisse merger la PR.

2016-12-13 15:39 UTC, merged