Ajout du bouton
uwp-squad/livecoding-uwp pull request #26
Opened 2017-03-30 14:52 UTC by andre726

2017-03-31 12:04 UTC, Odonno requested changes

2017-03-31 12:04 UTC, Odonno commented on LIvecoding-uwp/Livecoding/ViewModels/ChatList.cs
> +    class ChatList : ListViewItem
Pourquoi cette classe ? Si elle ne fait rien de précis, elle ne doit pas exister. De plus, si c'est pour gérer l'affichage d'une ListView pour le chat, tu peux le faire sans difficulté dans la View et le ViewModel.

2017-03-31 12:04 UTC, Odonno commented on LIvecoding-uwp/Livecoding/Views/StreamPage.xaml
> +                    <AppBarButton x:Name="ChatButton"
Il me semble que cet `AppBarButton` doit être intégré au contrôle `LivecodingMediaTransportControls`. Normalement, le template de ce contrôle est dans `App.xaml.cs`.

2017-03-31 12:04 UTC, Odonno commented on LIvecoding-uwp/Livecoding/Views/StreamPage.xaml
> +                                          VerticalAlignment="Center"
Il manque la balise de fermeture `/>`

2017-03-31 12:04 UTC, Odonno commented on LIvecoding-uwp/Livecoding/Views/StreamPage.xaml
> +            </MediaPlayerElement.TransportControls>
Déjà présent. A supprimer.

2017-03-31 12:04 UTC, Odonno commented on LIvecoding-uwp/Livecoding/Views/StreamPage.xaml
> +            </MediaPlayerElement>
Déjà présent. A supprimer.

2017-03-31 12:04 UTC, Odonno commented on LIvecoding-uwp/Livecoding/Views/StreamPage.xaml
> +            <ListViewItem x:Name="ChatList" IsEnabled="False" Visibility="Collapsed"/>
A déplacer en dehors du contrôle `MediaPlayerElement`.

2017-03-31 12:04 UTC, Odonno commented on LIvecoding-uwp/Livecoding/Views/StreamPage.xaml
> +            <ListViewItem x:Name="ChatList" IsEnabled="False" Visibility="Collapsed"/>
Je te conseille d'utiliser le contrôle `ListView` plutôt que `ListViewItem`  Et aussi, pourquoi utiliser la propriété `IsEnabled`, la propriété `Visibility` est amplement suffisante.

2017-04-02 14:42 UTC, andre726 commented on LIvecoding-uwp/Livecoding/ViewModels/ChatList.cs
> +    class ChatList : ListViewItem
je vooulais la faire pour gerer les options du chat

2017-04-02 14:47 UTC, andre726 commented on LIvecoding-uwp/Livecoding/Views/StreamPage.xaml
> +                    <AppBarButton x:Name="ChatButton"
tu peut détaillé?

2017-04-03 10:10 UTC, Odonno commented on LIvecoding-uwp/Livecoding/ViewModels/ChatList.cs
> +    class ChatList : ListViewItem
Tu dois modifier 2 fichiers principalement : la `StreamPage` et le `StreamViewModel`. En gros, la vue et la logique de la vue.

Dans le ViewModel, il faut par exemple que tu ajoutes la propriété suivante : 

```
private bool _showChat;
public bool ShowChat
{
    get { return _showChat; }
    set { _showChat = value; RaisePropertyChanged(); }
}
```

Et après dans la vue, tu fais le binding.

2017-04-03 11:15 UTC, Odonno requested changes

2017-04-03 11:15 UTC, Odonno commented on LIvecoding-uwp/Livecoding/Views/StreamPage.xaml
> +        <ListView x:Name="ChatList" Visibility="Collapsed"  />
A renommer en `ChatListView`.

2017-04-03 11:15 UTC, Odonno commented on LIvecoding-uwp/Livecoding/Views/StreamPage.xaml
> +        <ListView x:Name="ChatList" Visibility="Collapsed"  />
Pour mettre à jour le fait qu'elle soit visible : `Visibility={Binding Path=ShowChat}`

2017-04-03 11:15 UTC, Odonno commented on LIvecoding-uwp/Livecoding/Views/StreamPage.xaml
> +                                          Onclick="ChatHide_Show">
Inutile de mettre un event `OnClick`, il faudra passer par une `Command`.

2017-04-03 11:15 UTC, Odonno commented on LIvecoding-uwp/Livecoding/Views/StreamPage.xaml
> +                                <controls:AppBarButton x:Name="ChatButton"
Idem que la fois précédente, à placer dans `App.xaml.cs`

2017-04-03 11:15 UTC, Odonno commented on LIvecoding-uwp/Livecoding/Views/StreamPage.xaml
> +                                          DataContext="{Binding ShowChat, Source = {StaticRessource Locator}}"
Pas besoin de `DataContext`.

2017-04-03 11:17 UTC, Odonno commented on LIvecoding-uwp/Livecoding/ViewModels/StreamViewModel.cs
> +        public ListView ChatList
A remplacer par `public ObservableCollection<ChatMessage> Messages { get; } = new ObservableCollection<ChatMessage>();`

2017-04-03 13:40 UTC, andre726 commented on LIvecoding-uwp/Livecoding/Views/StreamPage.xaml
> +                                          Onclick="ChatHide_Show">
quelle est la différence?

2017-04-03 14:58 UTC, Odonno commented on LIvecoding-uwp/Livecoding/Views/StreamPage.xaml
> +                                          Onclick="ChatHide_Show">
Si tu passes par des events comme OnClick par exemple, tu vas devoir gérer la logique dans le code-behind, ce qui est à éviter dans 99% des cas.

Si tu passes par une `Command`, tu vas pouvoir manipuler la logique dans le ViewModel. Tu peux prendre exemple sur ce ViewModel https://github.com/uwp-squad/livecoding-uwp/blob/master/LIvecoding-uwp/Livecoding/ViewModels/LivestreamsViewModel.cs#L50

2017-04-04 20:17 UTC, andre726 commented on LIvecoding-uwp/Livecoding/Views/StreamPage.xaml
> +                                <controls:AppBarButton x:Name="ChatButton"
mais c'est du xaml ici, pas du c#

2017-04-05 08:09 UTC, Odonno commented on LIvecoding-uwp/Livecoding/Views/StreamPage.xaml
> +                                <controls:AppBarButton x:Name="ChatButton"
Je me suis trompé, c'est dans `App.xaml`

2017-04-05 19:07 UTC, Odonno commented on LIvecoding-uwp/Livecoding/Views/StreamPage.xaml
> +                                          Onclick="ChatHide_Show">
Le bouton devrait se situer à proximité des autres boutons ici https://github.com/uwp-squad/livecoding-uwp/blob/master/LIvecoding-uwp/Livecoding/App.xaml#L728

2017-04-05 19:09 UTC, Odonno commented on LIvecoding-uwp/Livecoding/Views/StreamPage.xaml
> +                                          Onclick="ChatHide_Show">
Et dans l'immédiat, tu peux faire un binding direct sur la commande de ton ViewModel pour voir ce que ça donne. Je vois pas d'autre solution simple pour le moment.

2017-04-06 07:52 UTC, andre726 commented on LIvecoding-uwp/Livecoding/Views/StreamPage.xaml
> +                                <controls:AppBarButton x:Name="ChatButton"
ok, je vais chercher pour voir ou le mettre :)

2017-04-20 22:30 UTC, Odonno requested changes

2017-04-20 22:30 UTC, Odonno commented on LIvecoding-uwp/Livecoding/App.xaml
> +
Suppression de la ligne en trop

2017-04-20 22:30 UTC, Odonno commented on LIvecoding-uwp/Livecoding/App.xaml
> +
Suppression de la ligne en trop

2017-04-20 22:30 UTC, Odonno commented on LIvecoding-uwp/Livecoding/App.xaml
> +                                                                      Visibility="Collapsed"
Le bouton est censé être toujours visible, non ? Ligne à supprimer.

2017-04-20 22:30 UTC, Odonno commented on LIvecoding-uwp/Livecoding/App.xaml
> +                                                                      Command="ChatVisibilityChange">
Voilà comment on écrit une commande généralement : 

```
Command="{Binding ShowChatCommand}"
```

2017-04-20 22:30 UTC, Odonno commented on LIvecoding-uwp/Livecoding/App.xaml
> +
Suppression des lignes en trop

2017-04-20 22:30 UTC, Odonno commented on LIvecoding-uwp/Livecoding/ViewModels/StreamViewModel.cs
> +        public ObservableCollection<ChatMessage> Messages { get; } = new ObservableCollection<ChatMessage>();
Ok, en fait la classe ChatMessage est déjà utilisé par l'OS. Il faudra créer une classe dans le dossier Models. Tu peux l'appeler LivecodingChatMessage par exemple. Et il doit y avoir les propriétés spécifiques d'un message, comme par exemple le username, le contenu du message et la date.

2017-04-20 22:30 UTC, Odonno commented on LIvecoding-uwp/Livecoding/Views/StreamPage.xaml
> +    xmlns:controls="using:Windows.UI.Xaml.Controls"
Suppression de la ligne en trop

2017-04-20 22:30 UTC, Odonno commented on LIvecoding-uwp/Livecoding/Views/StreamPage.xaml
> +
Suppression des lignes en trop

2017-04-20 22:30 UTC, Odonno commented on LIvecoding-uwp/Livecoding/Views/StreamPage.xaml
> +
Suppression des lignes en trop

2017-04-20 22:30 UTC, Odonno commented on LIvecoding-uwp/Livecoding/Views/StreamPage.xaml
> +
Suppression des lignes en trop

2017-04-20 22:30 UTC, Odonno commented on LIvecoding-uwp/Livecoding/Views/StreamPage.xaml
> +
Suppression des lignes en trop

2017-04-20 22:30 UTC, Odonno commented on LIvecoding-uwp/Livecoding/App.xaml
> +                                                                <FontIcon Glyph="comment"/>
Il me semble qu'il y a une majuscule pour le nom d'une glyph. Donc ce serait `Comment` plutôt.

2017-04-20 22:32 UTC, Odonno commented
Pour ce qui est de la commande, il faudra la créer dans le ViewModel. Regarde des exemples si cela peut t'aider. Comme par ici : https://github.com/uwp-squad/livecoding-uwp/blob/master/LIvecoding-uwp/Livecoding/ViewModels/LivestreamsViewModel.cs#L37

2017-04-20 22:32 UTC, Odonno commented on LIvecoding-uwp/Livecoding/App.xaml
> +                                                                      Command="ChatVisibilityChange">
Dans notre cas, je pense plutôt qu'il faut l'appeler `ToggleChatCommand`.

2026-03-07 17:10 UTC, closed without merging